library(dplyr)
unzip("exdata%2Fdata%2Fhousehold_power_consumption.zip")
HPDF<-read.table(file="household_power_consumption.txt", sep=";",header=TRUE)
HPDF$Date<-as.Date(HPDF$Date,"%d/%m/%Y")
HPDF_filter<-filter(HPDF,Date=="2007-02-01" | Date=="2007-02-02")
rm(HPDF)
png(file = "plot1.png", width = 480, height = 480)
hist(as.numeric(paste(HPDF_filter$Global_active_power)),main = "Global Active Power",col="red",ylab="Frequency", xlab="Global Active Power(kilowatts)")
dev.off()
