library(dplyr)
unzip("exdata%2Fdata%2Fhousehold_power_consumption.zip")
HPDF<-read.table(file="household_power_consumption.txt", sep=";",header=TRUE,na.strings = "?")
HPDF$Date<-as.Date(HPDF$Date,"%d/%m/%Y")
HPDF_filter<-filter(HPDF,Date=="2007-02-01" | Date=="2007-02-02")
HPDF_filter<-mutate(HPDF_filter,"DateTime" = as.POSIXct(paste(HPDF_filter$Date, HPDF_filter$Time)))
rm(HPDF)
png(file = "plot3.png", width = 480, height = 480)
plot(HPDF_filter$Sub_metering_1 ~ HPDF_filter$DateTime, type="s", xlab= "", ylab="Energy Sub Metering")
lines(HPDF_filter$Sub_metering_2 ~ HPDF_filter$DateTime, type="s", col="red")
lines(HPDF_filter$Sub_metering_3 ~ HPDF_filter$DateTime, type="s", col="blue")
legend("topright",lty=1,lwd=3, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
